################################################################################
MLI_FILE		= cordova_intent.mli
## Name which will be used in -package with ocamlfind
LIB_NAME		= cordova-plugin-intent
################################################################################
